INSERT INTO discovery.member(MEMBER_FIRST_NAME, MEMBER_LAST_NAME, MEMBER_EMAIL, MEMBER_PHONE) VALUES ('Caitlyn','Opperman','caitlynO@gmail.com','0712437485');
INSERT INTO discovery.account(MEMBER_ID, TYPE, BALANCE) VALUES (1,'MILES',250);
INSERT INTO discovery.transaction(ACCOUNT_NUMBER, AMOUNT, TRANSACTION_DATE) VALUES (1,100,'2021-09-25');
